/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ClickEarn Platform API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface OkResponse {
  ok: boolean;
}

export interface RegisterInput {
  /** @minLength 2 */
  name: string;
  email: string;
  /** @minLength 6 */
  password: string;
  /** @nullable */
  referralCode?: string | null;
}

export interface LoginInput {
  email: string;
  password: string;
}

export interface User {
  id: number;
  name: string;
  email: string;
  balance: number;
  pendingBalance: number;
  vipLevel: number;
  referralCode: string;
  isAdmin?: boolean;
  isBanned?: boolean;
  createdAt: string;
}

export interface AuthResponse {
  token: string;
  user: User;
}

export interface Wallet {
  balance: number;
  pendingBalance: number;
  totalEarned: number;
  totalWithdrawn: number;
}

export interface Transaction {
  id: number;
  type: string;
  amount: number;
  status: string;
  description: string;
  createdAt: string;
}

export interface WithdrawalInput {
  /** @minimum 5 */
  amount: number;
  method: string;
}

export interface VipLevel {
  level: number;
  name: string;
  requiredDeposit: number;
  earningsMultiplier: number;
  benefits: string[];
}

export interface DepositInput {
  /** @minimum 10 */
  amount: number;
  method: string;
}

export interface Task {
  id: number;
  title: string;
  description: string;
  reward: number;
  type: string;
  isCompleted: boolean;
  /** @nullable */
  expiresAt: string | null;
}

export interface TaskCompletion {
  success: boolean;
  reward: number;
  newBalance: number;
}

export interface Offer {
  id: number;
  title: string;
  description: string;
  reward: number;
  imageUrl: string;
  ctaLabel: string;
  ctaUrl: string;
  category: string;
}

export interface Ad {
  id: number;
  title: string;
  reward: number;
  imageUrl: string;
  adUrl: string;
  isClaimed: boolean;
}

export interface AdClaim {
  success: boolean;
  reward: number;
  newBalance: number;
}

export interface Survey {
  id: number;
  title: string;
  reward: number;
  lengthMinutes: number;
  url: string;
}

export interface SurveyPostbackInput {
  userId: number;
  transactionId: string;
  reward: number;
  hash: string;
}

export interface ReferralInfo {
  referralCode: string;
  referralLink: string;
  totalReferred: number;
  totalEarned: number;
}

export interface ReferredUser {
  id: number;
  name: string;
  joinedAt: string;
  earnings: number;
}

export interface Analytics {
  totalUsers: number;
  activeUsers: number;
  totalEarnings: number;
  totalWithdrawals: number;
  totalClicks: number;
  revenueToday: number;
  revenueWeek: number;
  revenueMonth: number;
}

export interface AdminUser {
  id: number;
  name: string;
  email: string;
  balance: number;
  vipLevel: number;
  isAdmin: boolean;
  isBanned: boolean;
  totalEarned: number;
  createdAt: string;
}

export interface AdminUserUpdate {
  /** @nullable */
  balance?: number | null;
  /** @nullable */
  vipLevel?: number | null;
  /** @nullable */
  isAdmin?: boolean | null;
  /** @nullable */
  isBanned?: boolean | null;
}

export interface AdminTransaction {
  id: number;
  userId: number;
  userName: string;
  type: string;
  amount: number;
  status: string;
  description: string;
  createdAt: string;
}

export interface PlatformSettings {
  monetagPublisherId: string;
  cpxAppId: string;
  cpxSecretKey: string;
  referralReward: number;
  adClickReward: number;
  withdrawalMinimum: number;
  withdrawalsEnabled: boolean;
}

export interface PlatformSettingsUpdate {
  /** @nullable */
  monetagPublisherId?: string | null;
  /** @nullable */
  cpxAppId?: string | null;
  /** @nullable */
  cpxSecretKey?: string | null;
  /** @nullable */
  referralReward?: number | null;
  /** @nullable */
  adClickReward?: number | null;
  /** @nullable */
  withdrawalMinimum?: number | null;
  /** @nullable */
  withdrawalsEnabled?: boolean | null;
}

