/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ClickEarn Platform API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Ad,
  AdClaim,
  AdminTransaction,
  AdminUser,
  AdminUserUpdate,
  Analytics,
  AuthResponse,
  DepositInput,
  HealthStatus,
  LoginInput,
  Offer,
  OkResponse,
  PlatformSettings,
  PlatformSettingsUpdate,
  ReferralInfo,
  ReferredUser,
  RegisterInput,
  Survey,
  SurveyPostbackInput,
  Task,
  TaskCompletion,
  Transaction,
  User,
  VipLevel,
  Wallet,
  WithdrawalInput
} from './api.schemas';

import { customFetch } from './custom-fetch';
import type { ErrorType , BodyType } from './custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getHealthCheckUrl = () => {




  return `/api/healthz`
}

/**
 * @summary Health check
 */
export const healthCheck = async ( options?: RequestInit): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getRegisterUrl = () => {




  return `/api/auth/register`
}

/**
 * @summary Register new user
 */
export const register = async (registerInput: RegisterInput, options?: RequestInit): Promise<AuthResponse> => {

  return customFetch<AuthResponse>(getRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerInput,)
  }
);}




export const getRegisterMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: BodyType<RegisterInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: BodyType<RegisterInput>}, TContext> => {

const mutationKey = ['register'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof register>>, {data: BodyType<RegisterInput>}> = (props) => {
          const {data} = props ?? {};

          return  register(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>
    export type RegisterMutationBody = BodyType<RegisterInput>
    export type RegisterMutationError = ErrorType<void>

    /**
 * @summary Register new user
 */
export const useRegister = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: BodyType<RegisterInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof register>>,
        TError,
        {data: BodyType<RegisterInput>},
        TContext
      > => {
      return useMutation(getRegisterMutationOptions(options));
    }

export const getLoginUrl = () => {




  return `/api/auth/login`
}

/**
 * @summary Login
 */
export const login = async (loginInput: LoginInput, options?: RequestInit): Promise<AuthResponse> => {

  return customFetch<AuthResponse>(getLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginInput,)
  }
);}




export const getLoginMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginInput>}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: BodyType<LoginInput>}> = (props) => {
          const {data} = props ?? {};

          return  login(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = BodyType<LoginInput>
    export type LoginMutationError = ErrorType<void>

    /**
 * @summary Login
 */
export const useLogin = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: BodyType<LoginInput>},
        TContext
      > => {
      return useMutation(getLoginMutationOptions(options));
    }

export const getGetMeUrl = () => {




  return `/api/auth/me`
}

/**
 * @summary Get current user
 */
export const getMe = async ( options?: RequestInit): Promise<User> => {

  return customFetch<User>(getGetMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMeQueryKey = () => {
    return [
    `/api/auth/me`
    ] as const;
    }


export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = ErrorType<unknown>


/**
 * @summary Get current user
 */

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetWalletUrl = () => {




  return `/api/wallet`
}

/**
 * @summary Get wallet info
 */
export const getWallet = async ( options?: RequestInit): Promise<Wallet> => {

  return customFetch<Wallet>(getGetWalletUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetWalletQueryKey = () => {
    return [
    `/api/wallet`
    ] as const;
    }


export const getGetWalletQueryOptions = <TData = Awaited<ReturnType<typeof getWallet>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getWallet>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWalletQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWallet>>> = ({ signal }) => getWallet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWallet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetWalletQueryResult = NonNullable<Awaited<ReturnType<typeof getWallet>>>
export type GetWalletQueryError = ErrorType<unknown>


/**
 * @summary Get wallet info
 */

export function useGetWallet<TData = Awaited<ReturnType<typeof getWallet>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getWallet>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetWalletQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetTransactionsUrl = () => {




  return `/api/wallet/transactions`
}

/**
 * @summary Get transaction history
 */
export const getTransactions = async ( options?: RequestInit): Promise<Transaction[]> => {

  return customFetch<Transaction[]>(getGetTransactionsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTransactionsQueryKey = () => {
    return [
    `/api/wallet/transactions`
    ] as const;
    }


export const getGetTransactionsQueryOptions = <TData = Awaited<ReturnType<typeof getTransactions>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTransactions>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTransactionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTransactions>>> = ({ signal }) => getTransactions({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTransactions>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTransactionsQueryResult = NonNullable<Awaited<ReturnType<typeof getTransactions>>>
export type GetTransactionsQueryError = ErrorType<unknown>


/**
 * @summary Get transaction history
 */

export function useGetTransactions<TData = Awaited<ReturnType<typeof getTransactions>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTransactions>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTransactionsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getRequestWithdrawalUrl = () => {




  return `/api/wallet/withdraw`
}

/**
 * @summary Request withdrawal
 */
export const requestWithdrawal = async (withdrawalInput: WithdrawalInput, options?: RequestInit): Promise<Transaction> => {

  return customFetch<Transaction>(getRequestWithdrawalUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      withdrawalInput,)
  }
);}




export const getRequestWithdrawalMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestWithdrawal>>, TError,{data: BodyType<WithdrawalInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof requestWithdrawal>>, TError,{data: BodyType<WithdrawalInput>}, TContext> => {

const mutationKey = ['requestWithdrawal'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof requestWithdrawal>>, {data: BodyType<WithdrawalInput>}> = (props) => {
          const {data} = props ?? {};

          return  requestWithdrawal(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RequestWithdrawalMutationResult = NonNullable<Awaited<ReturnType<typeof requestWithdrawal>>>
    export type RequestWithdrawalMutationBody = BodyType<WithdrawalInput>
    export type RequestWithdrawalMutationError = ErrorType<unknown>

    /**
 * @summary Request withdrawal
 */
export const useRequestWithdrawal = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestWithdrawal>>, TError,{data: BodyType<WithdrawalInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof requestWithdrawal>>,
        TError,
        {data: BodyType<WithdrawalInput>},
        TContext
      > => {
      return useMutation(getRequestWithdrawalMutationOptions(options));
    }

export const getGetVipLevelsUrl = () => {




  return `/api/vip/levels`
}

/**
 * @summary Get all VIP levels
 */
export const getVipLevels = async ( options?: RequestInit): Promise<VipLevel[]> => {

  return customFetch<VipLevel[]>(getGetVipLevelsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetVipLevelsQueryKey = () => {
    return [
    `/api/vip/levels`
    ] as const;
    }


export const getGetVipLevelsQueryOptions = <TData = Awaited<ReturnType<typeof getVipLevels>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getVipLevels>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVipLevelsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVipLevels>>> = ({ signal }) => getVipLevels({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVipLevels>>, TError, TData> & { queryKey: QueryKey }
}

export type GetVipLevelsQueryResult = NonNullable<Awaited<ReturnType<typeof getVipLevels>>>
export type GetVipLevelsQueryError = ErrorType<unknown>


/**
 * @summary Get all VIP levels
 */

export function useGetVipLevels<TData = Awaited<ReturnType<typeof getVipLevels>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getVipLevels>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetVipLevelsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getDepositForVipUrl = () => {




  return `/api/vip/deposit`
}

/**
 * @summary Deposit to upgrade VIP
 */
export const depositForVip = async (depositInput: DepositInput, options?: RequestInit): Promise<Transaction> => {

  return customFetch<Transaction>(getDepositForVipUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      depositInput,)
  }
);}




export const getDepositForVipMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof depositForVip>>, TError,{data: BodyType<DepositInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof depositForVip>>, TError,{data: BodyType<DepositInput>}, TContext> => {

const mutationKey = ['depositForVip'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof depositForVip>>, {data: BodyType<DepositInput>}> = (props) => {
          const {data} = props ?? {};

          return  depositForVip(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DepositForVipMutationResult = NonNullable<Awaited<ReturnType<typeof depositForVip>>>
    export type DepositForVipMutationBody = BodyType<DepositInput>
    export type DepositForVipMutationError = ErrorType<unknown>

    /**
 * @summary Deposit to upgrade VIP
 */
export const useDepositForVip = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof depositForVip>>, TError,{data: BodyType<DepositInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof depositForVip>>,
        TError,
        {data: BodyType<DepositInput>},
        TContext
      > => {
      return useMutation(getDepositForVipMutationOptions(options));
    }

export const getGetTasksUrl = () => {




  return `/api/tasks`
}

/**
 * @summary List available tasks
 */
export const getTasks = async ( options?: RequestInit): Promise<Task[]> => {

  return customFetch<Task[]>(getGetTasksUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTasksQueryKey = () => {
    return [
    `/api/tasks`
    ] as const;
    }


export const getGetTasksQueryOptions = <TData = Awaited<ReturnType<typeof getTasks>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTasksQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTasks>>> = ({ signal }) => getTasks({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTasksQueryResult = NonNullable<Awaited<ReturnType<typeof getTasks>>>
export type GetTasksQueryError = ErrorType<unknown>


/**
 * @summary List available tasks
 */

export function useGetTasks<TData = Awaited<ReturnType<typeof getTasks>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTasksQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCompleteTaskUrl = (taskId: number,) => {




  return `/api/tasks/${taskId}/complete`
}

/**
 * @summary Mark task as complete
 */
export const completeTask = async (taskId: number, options?: RequestInit): Promise<TaskCompletion> => {

  return customFetch<TaskCompletion>(getCompleteTaskUrl(taskId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getCompleteTaskMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeTask>>, TError,{taskId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof completeTask>>, TError,{taskId: number}, TContext> => {

const mutationKey = ['completeTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeTask>>, {taskId: number}> = (props) => {
          const {taskId} = props ?? {};

          return  completeTask(taskId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CompleteTaskMutationResult = NonNullable<Awaited<ReturnType<typeof completeTask>>>

    export type CompleteTaskMutationError = ErrorType<unknown>

    /**
 * @summary Mark task as complete
 */
export const useCompleteTask = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeTask>>, TError,{taskId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof completeTask>>,
        TError,
        {taskId: number},
        TContext
      > => {
      return useMutation(getCompleteTaskMutationOptions(options));
    }

export const getGetOffersUrl = () => {




  return `/api/offers`
}

/**
 * @summary List partner offers
 */
export const getOffers = async ( options?: RequestInit): Promise<Offer[]> => {

  return customFetch<Offer[]>(getGetOffersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetOffersQueryKey = () => {
    return [
    `/api/offers`
    ] as const;
    }


export const getGetOffersQueryOptions = <TData = Awaited<ReturnType<typeof getOffers>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOffers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOffersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOffers>>> = ({ signal }) => getOffers({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOffers>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOffersQueryResult = NonNullable<Awaited<ReturnType<typeof getOffers>>>
export type GetOffersQueryError = ErrorType<unknown>


/**
 * @summary List partner offers
 */

export function useGetOffers<TData = Awaited<ReturnType<typeof getOffers>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOffers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetOffersQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetAdsUrl = () => {




  return `/api/ads`
}

/**
 * @summary Get ad wall
 */
export const getAds = async ( options?: RequestInit): Promise<Ad[]> => {

  return customFetch<Ad[]>(getGetAdsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdsQueryKey = () => {
    return [
    `/api/ads`
    ] as const;
    }


export const getGetAdsQueryOptions = <TData = Awaited<ReturnType<typeof getAds>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAds>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAds>>> = ({ signal }) => getAds({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAds>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAdsQueryResult = NonNullable<Awaited<ReturnType<typeof getAds>>>
export type GetAdsQueryError = ErrorType<unknown>


/**
 * @summary Get ad wall
 */

export function useGetAds<TData = Awaited<ReturnType<typeof getAds>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAds>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAdsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getClaimAdUrl = (adId: number,) => {




  return `/api/ads/${adId}/claim`
}

/**
 * @summary Claim ad reward
 */
export const claimAd = async (adId: number, options?: RequestInit): Promise<AdClaim> => {

  return customFetch<AdClaim>(getClaimAdUrl(adId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getClaimAdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimAd>>, TError,{adId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof claimAd>>, TError,{adId: number}, TContext> => {

const mutationKey = ['claimAd'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof claimAd>>, {adId: number}> = (props) => {
          const {adId} = props ?? {};

          return  claimAd(adId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClaimAdMutationResult = NonNullable<Awaited<ReturnType<typeof claimAd>>>

    export type ClaimAdMutationError = ErrorType<unknown>

    /**
 * @summary Claim ad reward
 */
export const useClaimAd = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimAd>>, TError,{adId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof claimAd>>,
        TError,
        {adId: number},
        TContext
      > => {
      return useMutation(getClaimAdMutationOptions(options));
    }

export const getGetSurveysUrl = () => {




  return `/api/surveys`
}

/**
 * @summary Get available CPX surveys
 */
export const getSurveys = async ( options?: RequestInit): Promise<Survey[]> => {

  return customFetch<Survey[]>(getGetSurveysUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSurveysQueryKey = () => {
    return [
    `/api/surveys`
    ] as const;
    }


export const getGetSurveysQueryOptions = <TData = Awaited<ReturnType<typeof getSurveys>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSurveys>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSurveysQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSurveys>>> = ({ signal }) => getSurveys({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSurveys>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSurveysQueryResult = NonNullable<Awaited<ReturnType<typeof getSurveys>>>
export type GetSurveysQueryError = ErrorType<unknown>


/**
 * @summary Get available CPX surveys
 */

export function useGetSurveys<TData = Awaited<ReturnType<typeof getSurveys>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSurveys>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetSurveysQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getSurveyPostbackUrl = () => {




  return `/api/surveys/postback`
}

/**
 * @summary CPX Research postback
 */
export const surveyPostback = async (surveyPostbackInput: SurveyPostbackInput, options?: RequestInit): Promise<OkResponse> => {

  return customFetch<OkResponse>(getSurveyPostbackUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      surveyPostbackInput,)
  }
);}




export const getSurveyPostbackMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof surveyPostback>>, TError,{data: BodyType<SurveyPostbackInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof surveyPostback>>, TError,{data: BodyType<SurveyPostbackInput>}, TContext> => {

const mutationKey = ['surveyPostback'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof surveyPostback>>, {data: BodyType<SurveyPostbackInput>}> = (props) => {
          const {data} = props ?? {};

          return  surveyPostback(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SurveyPostbackMutationResult = NonNullable<Awaited<ReturnType<typeof surveyPostback>>>
    export type SurveyPostbackMutationBody = BodyType<SurveyPostbackInput>
    export type SurveyPostbackMutationError = ErrorType<unknown>

    /**
 * @summary CPX Research postback
 */
export const useSurveyPostback = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof surveyPostback>>, TError,{data: BodyType<SurveyPostbackInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof surveyPostback>>,
        TError,
        {data: BodyType<SurveyPostbackInput>},
        TContext
      > => {
      return useMutation(getSurveyPostbackMutationOptions(options));
    }

export const getGetReferralUrl = () => {




  return `/api/referral`
}

/**
 * @summary Get referral info
 */
export const getReferral = async ( options?: RequestInit): Promise<ReferralInfo> => {

  return customFetch<ReferralInfo>(getGetReferralUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetReferralQueryKey = () => {
    return [
    `/api/referral`
    ] as const;
    }


export const getGetReferralQueryOptions = <TData = Awaited<ReturnType<typeof getReferral>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getReferral>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReferralQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReferral>>> = ({ signal }) => getReferral({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReferral>>, TError, TData> & { queryKey: QueryKey }
}

export type GetReferralQueryResult = NonNullable<Awaited<ReturnType<typeof getReferral>>>
export type GetReferralQueryError = ErrorType<unknown>


/**
 * @summary Get referral info
 */

export function useGetReferral<TData = Awaited<ReturnType<typeof getReferral>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getReferral>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetReferralQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetReferredUsersUrl = () => {




  return `/api/referral/referred`
}

/**
 * @summary Get referred users
 */
export const getReferredUsers = async ( options?: RequestInit): Promise<ReferredUser[]> => {

  return customFetch<ReferredUser[]>(getGetReferredUsersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetReferredUsersQueryKey = () => {
    return [
    `/api/referral/referred`
    ] as const;
    }


export const getGetReferredUsersQueryOptions = <TData = Awaited<ReturnType<typeof getReferredUsers>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getReferredUsers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReferredUsersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReferredUsers>>> = ({ signal }) => getReferredUsers({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReferredUsers>>, TError, TData> & { queryKey: QueryKey }
}

export type GetReferredUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getReferredUsers>>>
export type GetReferredUsersQueryError = ErrorType<unknown>


/**
 * @summary Get referred users
 */

export function useGetReferredUsers<TData = Awaited<ReturnType<typeof getReferredUsers>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getReferredUsers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetReferredUsersQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetAnalyticsUrl = () => {




  return `/api/admin/analytics`
}

/**
 * @summary Admin analytics overview
 */
export const getAnalytics = async ( options?: RequestInit): Promise<Analytics> => {

  return customFetch<Analytics>(getGetAnalyticsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAnalyticsQueryKey = () => {
    return [
    `/api/admin/analytics`
    ] as const;
    }


export const getGetAnalyticsQueryOptions = <TData = Awaited<ReturnType<typeof getAnalytics>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAnalytics>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAnalyticsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAnalytics>>> = ({ signal }) => getAnalytics({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAnalytics>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAnalyticsQueryResult = NonNullable<Awaited<ReturnType<typeof getAnalytics>>>
export type GetAnalyticsQueryError = ErrorType<unknown>


/**
 * @summary Admin analytics overview
 */

export function useGetAnalytics<TData = Awaited<ReturnType<typeof getAnalytics>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAnalytics>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAnalyticsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetAdminUsersUrl = () => {




  return `/api/admin/users`
}

/**
 * @summary List all users
 */
export const getAdminUsers = async ( options?: RequestInit): Promise<AdminUser[]> => {

  return customFetch<AdminUser[]>(getGetAdminUsersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminUsersQueryKey = () => {
    return [
    `/api/admin/users`
    ] as const;
    }


export const getGetAdminUsersQueryOptions = <TData = Awaited<ReturnType<typeof getAdminUsers>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminUsers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminUsersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminUsers>>> = ({ signal }) => getAdminUsers({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminUsers>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAdminUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminUsers>>>
export type GetAdminUsersQueryError = ErrorType<unknown>


/**
 * @summary List all users
 */

export function useGetAdminUsers<TData = Awaited<ReturnType<typeof getAdminUsers>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminUsers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAdminUsersQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getUpdateAdminUserUrl = (userId: number,) => {




  return `/api/admin/users/${userId}`
}

/**
 * @summary Update user (balance, ban, etc.)
 */
export const updateAdminUser = async (userId: number,
    adminUserUpdate: AdminUserUpdate, options?: RequestInit): Promise<AdminUser> => {

  return customFetch<AdminUser>(getUpdateAdminUserUrl(userId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      adminUserUpdate,)
  }
);}




export const getUpdateAdminUserMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminUser>>, TError,{userId: number;data: BodyType<AdminUserUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAdminUser>>, TError,{userId: number;data: BodyType<AdminUserUpdate>}, TContext> => {

const mutationKey = ['updateAdminUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAdminUser>>, {userId: number;data: BodyType<AdminUserUpdate>}> = (props) => {
          const {userId,data} = props ?? {};

          return  updateAdminUser(userId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateAdminUserMutationResult = NonNullable<Awaited<ReturnType<typeof updateAdminUser>>>
    export type UpdateAdminUserMutationBody = BodyType<AdminUserUpdate>
    export type UpdateAdminUserMutationError = ErrorType<unknown>

    /**
 * @summary Update user (balance, ban, etc.)
 */
export const useUpdateAdminUser = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminUser>>, TError,{userId: number;data: BodyType<AdminUserUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateAdminUser>>,
        TError,
        {userId: number;data: BodyType<AdminUserUpdate>},
        TContext
      > => {
      return useMutation(getUpdateAdminUserMutationOptions(options));
    }

export const getGetAdminTransactionsUrl = () => {




  return `/api/admin/transactions`
}

/**
 * @summary List all transactions
 */
export const getAdminTransactions = async ( options?: RequestInit): Promise<AdminTransaction[]> => {

  return customFetch<AdminTransaction[]>(getGetAdminTransactionsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminTransactionsQueryKey = () => {
    return [
    `/api/admin/transactions`
    ] as const;
    }


export const getGetAdminTransactionsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminTransactions>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminTransactions>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminTransactionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminTransactions>>> = ({ signal }) => getAdminTransactions({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminTransactions>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAdminTransactionsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminTransactions>>>
export type GetAdminTransactionsQueryError = ErrorType<unknown>


/**
 * @summary List all transactions
 */

export function useGetAdminTransactions<TData = Awaited<ReturnType<typeof getAdminTransactions>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminTransactions>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAdminTransactionsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetAdminSettingsUrl = () => {




  return `/api/admin/settings`
}

/**
 * @summary Get platform settings
 */
export const getAdminSettings = async ( options?: RequestInit): Promise<PlatformSettings> => {

  return customFetch<PlatformSettings>(getGetAdminSettingsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminSettingsQueryKey = () => {
    return [
    `/api/admin/settings`
    ] as const;
    }


export const getGetAdminSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminSettings>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminSettings>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminSettingsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminSettings>>> = ({ signal }) => getAdminSettings({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminSettings>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAdminSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminSettings>>>
export type GetAdminSettingsQueryError = ErrorType<unknown>


/**
 * @summary Get platform settings
 */

export function useGetAdminSettings<TData = Awaited<ReturnType<typeof getAdminSettings>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminSettings>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAdminSettingsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getUpdateAdminSettingsUrl = () => {




  return `/api/admin/settings`
}

/**
 * @summary Update platform settings
 */
export const updateAdminSettings = async (platformSettingsUpdate: PlatformSettingsUpdate, options?: RequestInit): Promise<PlatformSettings> => {

  return customFetch<PlatformSettings>(getUpdateAdminSettingsUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      platformSettingsUpdate,)
  }
);}




export const getUpdateAdminSettingsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminSettings>>, TError,{data: BodyType<PlatformSettingsUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAdminSettings>>, TError,{data: BodyType<PlatformSettingsUpdate>}, TContext> => {

const mutationKey = ['updateAdminSettings'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAdminSettings>>, {data: BodyType<PlatformSettingsUpdate>}> = (props) => {
          const {data} = props ?? {};

          return  updateAdminSettings(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateAdminSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof updateAdminSettings>>>
    export type UpdateAdminSettingsMutationBody = BodyType<PlatformSettingsUpdate>
    export type UpdateAdminSettingsMutationError = ErrorType<unknown>

    /**
 * @summary Update platform settings
 */
export const useUpdateAdminSettings = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAdminSettings>>, TError,{data: BodyType<PlatformSettingsUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateAdminSettings>>,
        TError,
        {data: BodyType<PlatformSettingsUpdate>},
        TContext
      > => {
      return useMutation(getUpdateAdminSettingsMutationOptions(options));
    }

